# DeepSearchQA, Qwen3-32B, no models, 1 GPU
log_dir: logs/qwen3_32b_deepsearchqa_nomodel

_compose:
  - configs/experiment_base/inference_vllm_1gpu.yaml
  - configs/experiment_base/model_qwen3_32b.yaml
  - configs/experiment_base/model_search_tool_qwen3_32b.yaml
  - configs/experiment_base/benchmark_deepsearchqa.yaml

agent:
  configs:
    - configs/agents/deepsearchqa_nomodel.yaml
  version: deepsearchqa_nomodel_0.0.1
